title: Project Adventure
description: An adventure game created by Tom Albans
show_downloads: true
google_analytics:
theme: jekyll-theme-architect
include: ['_posts']
baseurl: /Project-Adventure
url: 'tom56785.github.io'

github:
  zip_url: https://github.com/Tom56785/Project-Adventure/archive/master.zip
  tar_url: https://github.com/Tom56785/Project-Adventure/archive/master.tar.gz
